---
keys:
  - &host_asc age15y7e536y0duw05v30u8m27rjq74kn3y7sszywrxu2kpzxdcx8f6qyqymfu
  - &host_ley age1z4z6atdekrwtcf5ntahgadnkdwz9cmc2mtj8c8g7l5vznwp3fytsd5e9c7
  - &user_c4300n age1qr30xfa47s84mcdcsp0h69x7ryflckmc20reyezc9wfysleeydvqc2v2y3

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *host_asc
          - *host_ley
          - *user_c4300n
